name: Hello World
on: workflow_dispatch

jobs:
  print_info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Information
        run: |
          pwd
          ls- ll
          echo "This is my first demo  Hello World"
      - name: Check out code
        uses: actions/checkout@v3
      - name: Print information after check out
        run: |
          ls -ll
    
